name: CI/CD Pipeline

on:
  schedule:
    - cron: '0 3 * * *' # run daily at 03:00 UTC
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: linea_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      
      redis:
        image: redis:7
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint frontend
        run: pnpm --filter @linea/web lint

      - name: Lint backend
        run: pnpm --filter @linea/api lint

      - name: Generate Prisma client
        run: pnpm --filter @linea/api db:generate

      - name: Run database migrations
        run: pnpm --filter @linea/api db:migrate
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/linea_test

      - name: Type check frontend
        run: pnpm --filter @linea/web typecheck

      - name: Type check backend
        run: pnpm --filter @linea/api typecheck

      - name: Build frontend
        run: pnpm --filter @linea/web build

      - name: Build backend
        run: pnpm --filter @linea/api build

      - name: Test frontend
        run: pnpm --filter @linea/web test

      - name: Test backend
        run: pnpm --filter @linea/api test
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/linea_test
          REDIS_URL: redis://localhost:6379
          JWT_SECRET: test-secret
          SESSION_SECRET: test-session-secret

